### ISSUE TITLE
Smart playlist doesn't get updated if a hidden copy exists

### ISSUE THREAD

**Issue by Houseman-HH** [rshea0/tuneup-prime#74]
### Issue description
If, for example, I subsequently change a tag such as comment or rating in a smartlist that has already been created, the title remains in the wrong list with the new changes.

I then have to manually delete the changed titles from the list.

After deleting and re-creating the list, the assignment is correct.

The biggest problem with this:
If I have recreated the smartlist with the changed tags and then synchronize it with my medium, the previously cleaned up smartlists are back to the old, faulty status!
But that seems to be a problem with Engine.
Unfortunately there is NO possibility to delete the files on the medium individually!
I reformatted my medium and re-synchronized the database - after that the correct smartlists were also on the medium - actually not a problem but extremely cumbersome

### Steps to reproduce
every time I change an tag like rating, comment and so on

### Environment

- `tuneup PRIME` version: 2.20
- Engine PRIME version: 2.10
- Operating System: Mac Monterey

**Comment by rshea0** [comment]
I haven't been able to reproduce the issue.

Here's what I've done
1. Create two smart playlists, `Test A` and `Test B` as follows:
```yaml
  - name: Test A
    rules:
      and:
        - [comment, contains, Test A]

  - name: Test B
    rules:
      and:
        - [comment, contains, Test B]
```
2. In Engine, set the comment of a track to `Test A`
3. Close Engine
3. Generate the playlists
4. Open Engine. As expected, the track is in playlist `Test A` and `Test B` is empty
6. Change the track's comment to `Test B`
7. Close Engine
8. Generate the playlists
9. Open Engine. Playlist `Test A` is now empty and the track is in `Test B` as it should be

Am I missing something?

**Comment by Houseman-HH** [comment]
Hi Ryan,

This is strange ...

I have now installed 2.31 and tried it again with myself.

I changed the 5 star rating of a track to 1 star.

Engine closed and TuneUp started.

Result:
The changed track with 1 star is still available in the 5 star list and does not appear in the 1 star list

I have attached my configuration file and my engine file to you once.

As I said - otherwise the lists work perfectly - I am only allowed to subsequently change tracks that are already in the lists - these changes are not accepted.

How can I send you the engine database - is over 200MB in size - it will not work by email

Do you have google drive or something?

I hope you can help me

Thanks

Holger

**Comment by Houseman-HH** [comment]
Hi Ryan,

Unfortunately I noticed another problem:

I have created a "GENRE" folder in Engine. In this you can find my smartlists including "HOUSE GENRE"

I deleted this smartlist in Engine and wanted to recreate it with TuneUp.

TuneUp creates it, but it is not visible in Engine! ?

Then I renamed the list in TuneUp to "HOUSE-GENRE"
what can I say- works and is visible

Then I repeated the same game - again not visible in the engine!

It seems that the list names that have already been used are not updated - that would also explain the problem with me with the changed tag entries - these are not removed or reassigned with with

Hope it helps you troubleshoot.

As already written, I would send you my engine database - unfortunately over 200 Mb in size


Thanks

Holger

**Comment by rshea0** [comment]
This is very strange...

No matter what I do I haven't been able to replicate the behavior. I've double checked and existing lists are being updated.

Try sending me your DB via Google Drive. Share it with shayded@shayded.com.

**Comment by rshea0** [comment]
AH! I found the issue.

Your DB has a second copy of all your smart playlists with their `isPersisted` flag off. It tells Engine whether or not to show the playlist. Because they were ordered first in the DB, Tuneup was updating those instead of the visible ones.

I went ahead and deleted all the hidden playlists from your DB and uploaded a fixed version back to the drive folder you shared. It should work now.

I should probably add a filter so Tuneup only looks for visible playlists.

**Comment by Houseman-HH** [comment]
Wow- you are the best!
Thank you for your help

I will try it

Holger

**Comment by Houseman-HH** [comment]
Hi Ryan,

I’m back again :(

Unfortunately, the old errors reappear - although changes to the tags are adopted in the updated lists, they also remain in the old lists at the same time.

This is really stupid

I can't imagine that this only happens to me.

My database is otherwise working perfectly

Maybe you still have an idea

Greets 

Holger

**Comment by rshea0** [comment]
Can you please update your DB file in the Drive folder along with your tuneup.yaml?

**Comment by Houseman-HH** [comment]
Done

**Comment by Houseman-HH** [comment]
Any news ?

**Comment by rshea0** [comment]
Haven't looked at it yet but I will tomorrow!

**Comment by rshea0** [comment]
I tested it out with your DB and tuneup.yaml and it seems to be working fine.

I tried changing the year of "Strangers By Nature - 7A - 55" from 2021 to 2022. It was correctly removed from the the 2021 playlist and added to the 2022 one. I changed the year back to 2021 and it was then removed from the 2022 playlist and added back to the 2021 as it should be.

Can you please isolate a specific track, change, and playlist you're seeing the issue with for me to test?

**Comment by Houseman-HH** [comment]
Hi Ryan,

Sorry - unfortunately I can’t.

I switched to Serato at short notice with the new Pioneer REV 7.

This has the advantage that I no longer annoy you :)

Thank you again for your support.

Regards

Holger
